# ------------------------------------------------------------------------------
# More resources related to this file:
# [1] Overview   | https://docs.docker.com/compose/
# [2] PostgreSQL | https://github.com/docker-library/docs/tree/master/postgres
# [3] Node.js    | https://github.com/nodejs/docker-node/blob/master/README.md#how-to-use-this-image
# -------------
#  More resources for your projects:
# [4] Samples    | https://github.com/docker/awesome-compose
# [5] Env Vars   | https://docs.docker.com/compose/environment-variables/
# [6] Secrets    | https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose
# ------------------------------------------------------------------------------

services:
  heroku-cli:
    build: ./heroku
    env_file: ./heroku/.env

  db:
    build: ./db
    env_file: .env
    volumes:
      - .db/init_data:/docker-entrypoint-initdb.d
      - db_volumes:/var/lib/postgresql/data

  web:
    build:
      context: ./
      dockerfile: dockerfile
      target: devapp
    env_file: .env
    depends_on:
      -   db
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app

volumes:
  db_volumes: {}
